@echo off
setlocal enabledelayedexpansion

REM Generates Windows app icons for Tauri from a single source image.
REM
REM How to use:
REM 1) Save your icon image as "%~dp0app-icon.png" (square PNG/SVG recommended).
REM 2) Double-click this script.
REM
REM Output:
REM - src-tauri\icons\icon.ico (used by Windows EXE/MSI/NSIS)
REM - Additional PNG sizes generated by `tauri icon`

cd /d "%~dp0"

if not exist "app-icon.png" (
  echo [ERROR] Missing file: app-icon.png
  echo         Please save the image as "%~dp0app-icon.png" and run again.
  echo.
  pause
  exit /b 1
)

if not exist "node_modules" (
  echo [ERROR] node_modules not found.
  echo         Run: npm install
  echo.
  pause
  exit /b 1
)

echo [INFO] Generating Tauri icons from: app-icon.png
echo        Output directory: src-tauri\icons
echo.

node scripts\run-tauri.cjs icon app-icon.png --output src-tauri\icons
if errorlevel 1 (
  echo.
  echo [ERROR] Icon generation failed.
  echo         Check terminal output above.
  echo.
  pause
  exit /b 1
)

echo.
echo [OK] Icons generated.
echo      - src-tauri\icons\icon.ico
echo      - src-tauri\icons\*.png
echo.
echo Next:
echo   - Rebuild installer: npm run tauri:build
echo.
pause
exit /b 0

